name: Deploy

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    # - name: Install R
    #   run: |
    #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    #     sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
    #     sudo apt update
    #     sudo apt install -y r-base
    # - name: Install base dependencies
    #   run: sudo apt-get update && sudo apt-get install -y build-essential && sudo apt-get install -y libcurl4-gnutls-dev && sudo apt-get install -y libxml2-dev && sudo apt-get install -y libssl-dev
    # - name: Install needed packages
    #   run: |
    #     sudo Rscript -e "install.packages('devtools')"
    #     sudo Rscript -e "install.packages('tidyverse')"
    #     sudo Rscript -e "install.packages('dotenv')"
    #     sudo Rscript -e "devtools::install_github('jpmarindiaz/mop')"
    #     sudo Rscript -e "devtools::install_github('bergant/airtabler')"
    # - name: Execute script
    #   env:
    #     AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
    #   run: |
    #     echo AIRTABLE_API_KEY=$AIRTABLE_API_KEY >> .env
    #     sudo Rscript ./scripts/generate-markdown-posts.R
    - name: Commit changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email action@github.com
        git add .
        git commit -m 'Updated build [skip ci]'
        echo $?
      # test $? -ne 0 && echo "There were no changes on generated reports" || git push origin master
